version: '3'
services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    volumes:
      - ./data:/data
      - ./spark_docker_sample:/app/spark_docker_sample
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - default

  
  spark-worker:
    image: bitnami/spark:latest
    volumes:
      - ./data:/data
      - ./spark_docker_sample:/app/spark_docker_sample
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
    networks:
      - default

  my-app:
    build: .
    container_name: my-app
    volumes:
      - ./data:/data
      - ./spark_docker_sample:/app/spark_docker_sample
    working_dir: /app
    command: >
      sh -c "spark-submit \
             --master spark://spark-master:7077 \
              spark_docker_sample/meucodigo.py "
    networks:
      - default         


networks:
  default:

